/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_guwei_volume_VolumeControl */

#ifndef _Included_com_guwei_volume_VolumeControl
#define _Included_com_guwei_volume_VolumeControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_guwei_volume_VolumeControl
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_guwei_volume_VolumeControl_init
  (JNIEnv *, jobject);

/*
 * Class:     com_guwei_volume_VolumeControl
 * Method:    setMasterVolume
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_guwei_volume_VolumeControl_setMasterVolume
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_guwei_volume_VolumeControl
 * Method:    getMasterVolume
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_guwei_volume_VolumeControl_getMasterVolume
  (JNIEnv *, jobject);

/*
 * Class:     com_guwei_volume_VolumeControl
 * Method:    setMute
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_guwei_volume_VolumeControl_setMute
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_guwei_volume_VolumeControl
 * Method:    getMute
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_guwei_volume_VolumeControl_getMute
  (JNIEnv *, jobject);

/*
 * Class:     com_guwei_volume_VolumeControl
 * Method:    finished
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_guwei_volume_VolumeControl_finished
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
